[package]
name = "fake-minecraft-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.0", features = [
  "macros",
  "rt-multi-thread",
  "net",
  "io-util",
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
