host: 127.0.0.1
port: 25565

status:
  version:
    name: 1.21.5
    protocol: 770
    same: false

  players:
    max: 20
    online: 0
    sample:
      - name: Player1
        id: b3a2c344-e57e-43f9-97a6-494d060f0d01
      - name: Player2
        id: c349b9ff-5c76-4831-b06b-d62c14791339

  description: "§cFake Minecraft Server"
  favicon: server-icon.png

kick_message: "§c§lThis is a fake server!\n§eIt only responds to ping requests."
